// SPDX-License-Identifier: Apache-2.0

//! Captures the terminal surface as an SVG for the product site
//! (sitio-web-producto task 2.4).
//!
//! This is a **real** capture: it drives the same renderer the shell uses, over
//! a fixture session set standing in for a temporary repository driven by the
//! simulated agent. Nothing is drawn by hand, so the image cannot drift into a
//! mockup — regenerate it and the current UI is what appears. It carries no
//! personal path, no identity and no third-party product name (design D5).
//!
//! Usage: `cargo run -p meltemi --example capture_svg > site/media/tui-sessions.svg`

use meltemi::shell::live::{LiveData, ProjectRow, SessionRow, Update};
use meltemi::shell::messages::Lang;
use meltemi::shell::present::{Presentation, PresentationEnv};
use meltemi::shell::render::{ConnState, ShellCtx, render};
use meltemi::shell::state::ShellState;
use meltemi_proto::SessionState;
use ratatui::Terminal;
use ratatui::backend::TestBackend;
use ratatui::style::Modifier;

const COLS: u16 = 96;
const ROWS: u16 = 24;
/// Monospace cell metrics of the SVG grid.
const CELL_W: f32 = 8.0;
const CELL_H: f32 = 18.0;

fn main() {
    let mut live = LiveData::new();
    live.apply(Update::Conn(ConnState::Connected {
        version: "0.1.0".into(),
        uptime_s: 1_845,
        sessions: 1,
    }));
    live.apply(Update::Pending(1));
    // Two fixture projects; the roots are deliberately generic.
    live.apply(Update::Projects(vec![
        ProjectRow {
            root: "/fixtures/harbour".into(),
            exists: true,
            sessions_total: 2,
            active_sessions: 1,
        },
        ProjectRow {
            root: "/fixtures/lighthouse".into(),
            exists: true,
            sessions_total: 1,
            active_sessions: 0,
        },
    ]));
    live.apply(Update::Sessions(vec![
        SessionRow {
            mode: None,
            model: None,
            id: "3f9c1a20".into(),
            agent: "mock-agent".into(),
            state: SessionState::Active,
            project_root: "/fixtures/harbour".into(),
            resumable: false,
            agent_id: Some("mock-agent".into()),
            profile: Some("work".into()),
            title: None,
        },
        SessionRow {
            mode: None,
            model: None,
            id: "7b21e4d8".into(),
            agent: "mock-agent".into(),
            state: SessionState::WaitingPermission,
            project_root: "/fixtures/harbour".into(),
            resumable: false,
            agent_id: Some("mock-agent".into()),
            profile: Some("personal".into()),
            title: None,
        },
        SessionRow {
            mode: None,
            model: None,
            id: "c04ab7f1".into(),
            agent: "mock-agent".into(),
            state: SessionState::Ended,
            project_root: "/fixtures/lighthouse".into(),
            resumable: true,
            agent_id: Some("mock-agent".into()),
            profile: None,
            title: None,
        },
    ]));

    let ctx = ShellCtx {
        present: Presentation::resolve(&PresentationEnv {
            lang: Some("en_US.UTF-8".into()),
            ..Default::default()
        }),
        lang: Lang::En,
        project: true,
    };
    let state = ShellState::new();

    let mut terminal = Terminal::new(TestBackend::new(COLS, ROWS)).expect("terminal");
    terminal
        .draw(|frame| render(frame, &state, &live, &ctx))
        .expect("draw");
    let buffer = terminal.backend().buffer().clone();

    let width = f32::from(COLS) * CELL_W;
    let height = f32::from(ROWS) * CELL_H;
    let mut svg = String::new();
    svg.push_str(&format!(
        concat!(
            "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 {w} {h}\" ",
            "width=\"{w}\" height=\"{h}\" role=\"img\">\n",
            "  <!-- SPDX-License-Identifier: Apache-2.0 -->\n",
            "  <!-- GENERATED by `cargo run -p meltemi --example capture_svg`. ",
            "A real render of the terminal surface over fixture data; do not edit. -->\n",
            "  <style>\n",
            "    .bg {{ fill: #0b1220; }}\n",
            "    .fg {{ fill: #e2e8f0; font-family: var(--font-mono, ui-monospace, monospace); ",
            "font-size: 13px; white-space: pre; }}\n",
            "    .rev {{ fill: #e2e8f0; }}\n",
            "    .revfg {{ fill: #0b1220; }}\n",
            "  </style>\n",
            "  <rect class=\"bg\" x=\"0\" y=\"0\" width=\"{w}\" height=\"{h}\" rx=\"8\"/>\n"
        ),
        w = width,
        h = height
    ));

    for row in 0..ROWS {
        // Group the row into runs sharing the reverse-video attribute, so the
        // focused line reads as focused in the image too.
        let mut runs: Vec<(u16, String, bool)> = Vec::new();
        for col in 0..COLS {
            let cell = &buffer[(col, row)];
            let reversed = cell.modifier.contains(Modifier::REVERSED);
            match runs.last_mut() {
                Some((_, text, run_reversed)) if *run_reversed == reversed => {
                    text.push_str(cell.symbol());
                }
                _ => runs.push((col, cell.symbol().to_string(), reversed)),
            }
        }
        let y = f32::from(row) * CELL_H;
        for (col, text, reversed) in runs {
            if text.trim().is_empty() && !reversed {
                continue;
            }
            let x = f32::from(col) * CELL_W;
            if reversed {
                let run_width = text.chars().count() as f32 * CELL_W;
                svg.push_str(&format!(
                    "  <rect class=\"rev\" x=\"{x}\" y=\"{y}\" width=\"{run_width}\" height=\"{CELL_H}\"/>\n"
                ));
            }
            let class = if reversed { "revfg" } else { "fg" };
            svg.push_str(&format!(
                "  <text class=\"{class}\" x=\"{x}\" y=\"{}\" xml:space=\"preserve\">{}</text>\n",
                y + CELL_H * 0.72,
                escape(&text)
            ));
        }
    }
    svg.push_str("</svg>\n");
    print!("{svg}");
}

/// XML-escapes a run of text.
fn escape(text: &str) -> String {
    text.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}
